# =========================================
# Staging environment setup
# =========================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: garage-staging

resources:
- ../dev/auth-service.yaml
- ../dev/microservices.yaml
- ../dev/infrastructure.yaml
- ../dev/kafka.yaml
- ../dev/rbac-and-ingress.yaml

commonLabels:
  environment: staging
  managed-by: kustomize

commonAnnotations:
  description: "STAGING environment for Garage Microservices"
  version: "1.0.0"

replicas:
- name: auth-service
  count: 2
- name: vehicle-service
  count: 2
- name: stock-service
  count: 2

# Patch replicas
patches:
- target:
    kind: HorizontalPodAutoscaler
    name: auth-service-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 5

- target:
    kind: HorizontalPodAutoscaler
    name: vehicle-service-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 5

- target:
    kind: HorizontalPodAutoscaler
    name: stock-service-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 5

images:
- name: docker.io/sjlassi/garage-microservices-auth
  newTag: staging
- name: docker.io/sjlassi/garage-microservices-vehicle
  newTag: staging
- name: docker.io/sjlassi/garage-microservices-stock
  newTag: staging

